// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v3.12.4
// source: proto/vault/vault.proto

package vault

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vault struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Url         string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Password    string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *Vault) Reset() {
	*x = Vault{}
	mi := &file_proto_vault_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vault) ProtoMessage() {}

func (x *Vault) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vault.ProtoReflect.Descriptor instead.
func (*Vault) Descriptor() ([]byte, []int) {
	return file_proto_vault_vault_proto_rawDescGZIP(), []int{0}
}

func (x *Vault) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Vault) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Vault) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Vault) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Vault) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type VaultGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *VaultGetRequest) Reset() {
	*x = VaultGetRequest{}
	mi := &file_proto_vault_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultGetRequest) ProtoMessage() {}

func (x *VaultGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultGetRequest.ProtoReflect.Descriptor instead.
func (*VaultGetRequest) Descriptor() ([]byte, []int) {
	return file_proto_vault_vault_proto_rawDescGZIP(), []int{1}
}

func (x *VaultGetRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type VaultGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vaults []*Vault `protobuf:"bytes,1,rep,name=vaults,proto3" json:"vaults,omitempty"`
	Error  string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *VaultGetResponse) Reset() {
	*x = VaultGetResponse{}
	mi := &file_proto_vault_vault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultGetResponse) ProtoMessage() {}

func (x *VaultGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_vault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultGetResponse.ProtoReflect.Descriptor instead.
func (*VaultGetResponse) Descriptor() ([]byte, []int) {
	return file_proto_vault_vault_proto_rawDescGZIP(), []int{2}
}

func (x *VaultGetResponse) GetVaults() []*Vault {
	if x != nil {
		return x.Vaults
	}
	return nil
}

func (x *VaultGetResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VaultDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *VaultDeleteRequest) Reset() {
	*x = VaultDeleteRequest{}
	mi := &file_proto_vault_vault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultDeleteRequest) ProtoMessage() {}

func (x *VaultDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_vault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultDeleteRequest.ProtoReflect.Descriptor instead.
func (*VaultDeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_vault_vault_proto_rawDescGZIP(), []int{3}
}

func (x *VaultDeleteRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type VaultDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *VaultDeleteResponse) Reset() {
	*x = VaultDeleteResponse{}
	mi := &file_proto_vault_vault_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultDeleteResponse) ProtoMessage() {}

func (x *VaultDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_vault_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultDeleteResponse.ProtoReflect.Descriptor instead.
func (*VaultDeleteResponse) Descriptor() ([]byte, []int) {
	return file_proto_vault_vault_proto_rawDescGZIP(), []int{4}
}

func (x *VaultDeleteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VaultCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Url         string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Password    string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *VaultCreateRequest) Reset() {
	*x = VaultCreateRequest{}
	mi := &file_proto_vault_vault_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultCreateRequest) ProtoMessage() {}

func (x *VaultCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_vault_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultCreateRequest.ProtoReflect.Descriptor instead.
func (*VaultCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_vault_vault_proto_rawDescGZIP(), []int{5}
}

func (x *VaultCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VaultCreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VaultCreateRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *VaultCreateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type VaultCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *VaultCreateResponse) Reset() {
	*x = VaultCreateResponse{}
	mi := &file_proto_vault_vault_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultCreateResponse) ProtoMessage() {}

func (x *VaultCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_vault_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultCreateResponse.ProtoReflect.Descriptor instead.
func (*VaultCreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_vault_vault_proto_rawDescGZIP(), []int{6}
}

func (x *VaultCreateResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VaultCreateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type VaultUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Url         string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	Password    string `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *VaultUpdateRequest) Reset() {
	*x = VaultUpdateRequest{}
	mi := &file_proto_vault_vault_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultUpdateRequest) ProtoMessage() {}

func (x *VaultUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_vault_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultUpdateRequest.ProtoReflect.Descriptor instead.
func (*VaultUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_vault_vault_proto_rawDescGZIP(), []int{7}
}

func (x *VaultUpdateRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VaultUpdateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VaultUpdateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VaultUpdateRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *VaultUpdateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type VaultUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Error string `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *VaultUpdateResponse) Reset() {
	*x = VaultUpdateResponse{}
	mi := &file_proto_vault_vault_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultUpdateResponse) ProtoMessage() {}

func (x *VaultUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_vault_vault_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultUpdateResponse.ProtoReflect.Descriptor instead.
func (*VaultUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_vault_vault_proto_rawDescGZIP(), []int{8}
}

func (x *VaultUpdateResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VaultUpdateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_vault_vault_proto protoreflect.FileDescriptor

var file_proto_vault_vault_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x2f, 0x76, 0x61,
	0x75, 0x6c, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x05, 0x56, 0x61, 0x75,
	0x6c, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x21, 0x0a, 0x0f, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x48, 0x0a, 0x10, 0x56, 0x61, 0x75,
	0x6c, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a,
	0x06, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06, 0x2e,
	0x56, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x22, 0x24, 0x0a, 0x12, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2b, 0x0a, 0x13, 0x56, 0x61, 0x75,
	0x6c, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x78, 0x0a, 0x12, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64,
	0x22, 0x3b, 0x0a, 0x13, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x88, 0x01,
	0x0a, 0x12, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x3b, 0x0a, 0x13, 0x56, 0x61, 0x75, 0x6c,
	0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x32, 0xed, 0x01, 0x0a, 0x0c, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x2f, 0x0a, 0x08, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x47,
	0x65, 0x74, 0x12, 0x10, 0x2e, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x56, 0x61, 0x75, 0x6c, 0x74,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x56, 0x61,
	0x75, 0x6c, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x38, 0x0a, 0x0b, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x13, 0x2e, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x56,
	0x61, 0x75, 0x6c, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x13, 0x2e, 0x56, 0x61, 0x75,
	0x6c, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x14, 0x2e, 0x56, 0x61, 0x75, 0x6c, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x7a, 0x69, 0x75, 0x6e, 0x69, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x36,
	0x39, 0x2f, 0x67, 0x6f, 0x70, 0x61, 0x73, 0x73, 0x61, 0x66, 0x65, 0x2d, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2f, 0x76, 0x61, 0x75, 0x6c, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_vault_vault_proto_rawDescOnce sync.Once
	file_proto_vault_vault_proto_rawDescData = file_proto_vault_vault_proto_rawDesc
)

func file_proto_vault_vault_proto_rawDescGZIP() []byte {
	file_proto_vault_vault_proto_rawDescOnce.Do(func() {
		file_proto_vault_vault_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_vault_vault_proto_rawDescData)
	})
	return file_proto_vault_vault_proto_rawDescData
}

var file_proto_vault_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_vault_vault_proto_goTypes = []any{
	(*Vault)(nil),               // 0: Vault
	(*VaultGetRequest)(nil),     // 1: VaultGetRequest
	(*VaultGetResponse)(nil),    // 2: VaultGetResponse
	(*VaultDeleteRequest)(nil),  // 3: VaultDeleteRequest
	(*VaultDeleteResponse)(nil), // 4: VaultDeleteResponse
	(*VaultCreateRequest)(nil),  // 5: VaultCreateRequest
	(*VaultCreateResponse)(nil), // 6: VaultCreateResponse
	(*VaultUpdateRequest)(nil),  // 7: VaultUpdateRequest
	(*VaultUpdateResponse)(nil), // 8: VaultUpdateResponse
}
var file_proto_vault_vault_proto_depIdxs = []int32{
	0, // 0: VaultGetResponse.vaults:type_name -> Vault
	1, // 1: VaultService.VaultGet:input_type -> VaultGetRequest
	5, // 2: VaultService.VaultCreate:input_type -> VaultCreateRequest
	7, // 3: VaultService.VaultUpdate:input_type -> VaultUpdateRequest
	3, // 4: VaultService.VaultDelete:input_type -> VaultDeleteRequest
	2, // 5: VaultService.VaultGet:output_type -> VaultGetResponse
	6, // 6: VaultService.VaultCreate:output_type -> VaultCreateResponse
	8, // 7: VaultService.VaultUpdate:output_type -> VaultUpdateResponse
	4, // 8: VaultService.VaultDelete:output_type -> VaultDeleteResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_vault_vault_proto_init() }
func file_proto_vault_vault_proto_init() {
	if File_proto_vault_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_vault_vault_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_vault_vault_proto_goTypes,
		DependencyIndexes: file_proto_vault_vault_proto_depIdxs,
		MessageInfos:      file_proto_vault_vault_proto_msgTypes,
	}.Build()
	File_proto_vault_vault_proto = out.File
	file_proto_vault_vault_proto_rawDesc = nil
	file_proto_vault_vault_proto_goTypes = nil
	file_proto_vault_vault_proto_depIdxs = nil
}
